title: HELibTech
description: A starting point for anyone interested in library technology in Higher Education
theme: just-the-docs
repository: librarieshacked/helibtech

logo: "/assets/images/logo-no-background.svg"

color_scheme: helibtech
search_enabled: true

footer_content: "Content on HELibTech is licensed under CC0 1.0 Universal. Please refer to re-use permissions on third party content linked to by HELibTech."

heading_anchors: true

back_to_top: true
back_to_top_text: "Back to top"

gh_edit_link: false # show or hide edit this page link

callouts:
  synopsis:
    color: yellow

collections:
  metatags:
    output: true

just_the_docs:
  collections:
    metatags:
      name: Metatags
      nav_exclude: true
      search_exclude: true
