title: helibtech
theme: just-the-docs

logo: "/assets/images/helibtech-logo.png"

color_scheme: light
search_enabled: true

footer_content: "Content on HELibTech is licensed under CC0 1.0 Universal. Please refer to re-use permissions on third party content linked to by HELibTech."

heading_anchors: true

back_to_top: true
back_to_top_text: "Back to top"

gh_edit_link: false # show or hide edit this page link

callouts:
  synopsis:
    title: Synopsis
    color: blue
