title: helibtech
theme: just-the-docs
logo: "/assets/images/helibtech-logo.png"
color_scheme: light
search_enabled: true

footer_content: "Some footer content"

gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/librarieshacked/helibtech"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"
