title: helibtech
theme: just-the-docs

logo: "/assets/images/helibtech-logo.png"

color_scheme: light
search_enabled: true

footer_content: "Except where otherwise noted, content on this wiki is licensed under the following license: CC0 1.0 Universal"

heading_anchors: true

back_to_top: true
back_to_top_text: "Back to top"

gh_edit_link: false # show or hide edit this page link
