backend:
  name: git-gateway
  branch: main

media_folder: "assets/images"

aliases:
  - &META_TAGS {
      label: "Metadata tags",
      name: "tags",
      widget: "select",
      multiple: true,
      options:
        [
          "News",
          "LSP",
          "Acquisitions",
          "Discovery",
          "Research Information Management System",
          "Apps",
          "Digitisation",
          "Special collections",
          "Events",
          "Library management systems",
          "Software",
          "Electronic resource management",
          "Open Access",
          "Collection management",
          "Engagement",
          "Research management",
          "Products",
          "Migration",
          "Hardware",
          "Institutional repository",
          "Research Data Management",
          "Collection development",
          "Learning & teaching",
          "Technology market",
          "Procurement",
          "Interlending",
          "RFID",
          "IR",
          "RDM",
          "Reading lists",
          "Etextbooks",
          "Library systems",
          "Resource sharing",
          "Authentication",
          "CRIS",
          "Chatbots",
          "Resource lists",
          "Ebooks",
          "LMS",
          "Controlled Digital Lending",
          "Artificial Intelligence",
          "Current research information system",
          "Enquiry management",
          "VLE",
          "Research metrics",
          "Library services platform",
          "CDL",
          "AI",
          "RIMS",
          "Data & analytics",
          "Virtual Learning Environment",
          "Archives",
        ],
    }

collections:
  - label: "Pages"
    name: "pages"
    files:
      - name: analytics_and_user_engagement_index
        label: Analytics and user engagement home
        file: analytics-and-user-engagement/index.md
        create: false
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
          - {
              label: "Layout",
              name: "layout",
              widget: "hidden",
              default: "default",
            }
          - {
              label: "Navigation order",
              name: "nav_order",
              widget: "hidden",
              default: 10,
            }
          - {
              label: "Has children",
              name: "has_children",
              widget: "hidden",
              default: true,
            }
          - <<: *META_TAGS

      - name: archives_and_special_collections_index
        label: Archives and special collections home
        file: archives-and-special-collections/index.md
        create: false
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
          - {
              label: "Layout",
              name: "layout",
              widget: "hidden",
              default: "default",
            }
          - {
              label: "Navigation order",
              name: "nav_order",
              widget: "hidden",
              default: 11,
            }
          - {
              label: "Has children",
              name: "has_children",
              widget: "hidden",
              default: true,
            }

      - name: core_library_systems_index
        label: Core library systems home
        file: core-library-systems/index.md
        create: false
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
          - {
              label: "Layout",
              name: "layout",
              widget: "hidden",
              default: "default",
            }
          - {
              label: "Navigation order",
              name: "nav_order",
              widget: "hidden",
              default: 6,
            }
          - {
              label: "Has children",
              name: "has_children",
              widget: "hidden",
              default: true,
            }

      - name: discovery_and_content_index
        label: Discovery and content home
        file: discovery-and-content/index.md
        create: false
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
          - {
              label: "Layout",
              name: "layout",
              widget: "hidden",
              default: "default",
            }
          - {
              label: "Navigation order",
              name: "nav_order",
              widget: "hidden",
              default: 7,
            }
          - {
              label: "Has children",
              name: "has_children",
              widget: "hidden",
              default: true,
            }

      - name: events_index
        label: Events home
        file: events/index.md
        create: false
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
          - {
              label: "Layout",
              name: "layout",
              widget: "hidden",
              default: "default",
            }
          - {
              label: "Navigation order",
              name: "nav_order",
              widget: "hidden",
              default: 3,
            }
          - {
              label: "Has children",
              name: "has_children",
              widget: "hidden",
              default: true,
            }

      - name: past_events_index
        label: Past events home
        file: events/past-events/index.md
        create: false
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
          - {
              label: "Layout",
              name: "layout",
              widget: "hidden",
              default: "default",
            }
          - {
              label: "Navigation order",
              name: "nav_order",
              widget: "hidden",
              default: 1,
            }
          - {
              label: "Has children",
              name: "has_children",
              widget: "hidden",
              default: true,
            }

      - name: learning_and_teaching_tech_index
        label: Learning and teaching tech home
        file: learning-and-teaching-tech/index.md
        create: false
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
          - {
              label: "Layout",
              name: "layout",
              widget: "hidden",
              default: "default",
            }
          - {
              label: "Navigation order",
              name: "nav_order",
              widget: "hidden",
              default: 8,
            }
          - {
              label: "Has children",
              name: "has_children",
              widget: "hidden",
              default: true,
            }

      - name: news_index
        label: News home
        file: news/index.md
        create: false
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
          - {
              label: "Layout",
              name: "layout",
              widget: "hidden",
              default: "default",
            }
          - {
              label: "Navigation order",
              name: "nav_order",
              widget: "hidden",
              default: 2,
            }
          - {
              label: "Has children",
              name: "has_children",
              widget: "hidden",
              default: true,
            }

      - name: news_archive_index
        label: News archive home
        file: news/archive/index.md
        create: false
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
          - {
              label: "Layout",
              name: "layout",
              widget: "hidden",
              default: "default",
            }
          - {
              label: "Navigation order",
              name: "nav_order",
              widget: "hidden",
              default: 1,
            }
          - {
              label: "Has children",
              name: "has_children",
              widget: "hidden",
              default: true,
            }

      - name: product_directory
        label: Product directory
        file: product-directory/index.md
        create: false
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
          - {
              label: "Layout",
              name: "layout",
              widget: "hidden",
              default: "sheet",
            }
          - {
              label: "Navigation order",
              name: "nav_order",
              widget: "hidden",
              default: 5,
            }
          - {
              label: "Has children",
              name: "has_children",
              widget: "hidden",
              default: false,
            }

      - name: research_management_index
        label: Research management home
        file: research-management/index.md
        create: false
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
          - {
              label: "Layout",
              name: "layout",
              widget: "hidden",
              default: "default",
            }
          - {
              label: "Navigation order",
              name: "nav_order",
              widget: "hidden",
              default: 9,
            }
          - {
              label: "Has children",
              name: "has_children",
              widget: "hidden",
              default: true,
            }

      - name: who_uses_what_index
        label: Who uses what home
        file: who-uses-what/index.md
        create: false
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
          - {
              label: "Layout",
              name: "layout",
              widget: "hidden",
              default: "default",
            }
          - {
              label: "Navigation order",
              name: "nav_order",
              widget: "hidden",
              default: 4,
            }
          - {
              label: "Has children",
              name: "has_children",
              widget: "hidden",
              default: true,
            }

  - name: "news_posts"
    label: "News posts"
    folder: "News"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    filter:
      field: parent
      value: News
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date added", name: "date", widget: "datetime" }
      - { label: "Synopsis", name: "synopsis", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Parent", name: "parent", widget: "hidden", default: "News" }
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "default",
        }
      - { label: "Metadata tags", name: "tags", widget: "markdown" }

  - name: "news_archive"
    label: "News archive"
    folder: "news/archive"
    create: false
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Source", name: "excerpt", widget: "string" }
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "default",
        }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Parent", name: "parent", widget: "hidden", default: "News" }
