backend:
  name: git-gateway
  branch: main

media_folder: "assets/images"

aliases:
  - &TITLE { label: "Title", name: "title", widget: "string" }
  - &BODY { label: "Body", name: "body", widget: "markdown" }
  - &DATE { label: "Date", name: "date", widget: "datetime" }
  - &DATE_ADDED { label: "Date added", name: "date_added", widget: "datetime" }
  - &SYNOPSIS { label: "Synopsis", name: "synopsis", widget: "markdown" }
  - &ABSTRACT { label: "Synopsis", name: "synopsis", widget: "markdown" }
  - &URL { label: "External URL", name: "url", widget: "string" }
  - &DEFAULT_LAYOUT {
      label: "Layout",
      name: "layout",
      widget: "hidden",
      default: "default",
    }
  - &META_TAGS {
      label: "Metadata tags",
      name: "tags",
      widget: "select",
      multiple: true,
      options:
        [
          "AI",
          "Acquisitions",
          "Archives",
          "Artificial Intelligence",
          "Authentication",
          "CDL",
          "CRIS",
          "Chatbots",
          "Collection development",
          "Collection management",
          "Controlled Digital Lending",
          "Current research information system",
          "Data & analytics",
          "Digitisation",
          "Discovery",
          "Ebooks",
          "Electronic resource management",
          "Enquiry management",
          "Engagement",
          "Etextbooks",
          "Events",
          "Hardware",
          "Institutional repository",
          "Interlending",
          "IR",
          "LMS",
          "Learning & teaching",
          "Library management systems",
          "Library services platform",
          "Library systems",
          "LSP",
          "Migration",
          "News",
          "Open Access",
          "Procurement",
          "Products",
          "Reading lists",
          "Research Data Management",
          "Research Information Management System",
          "Research management",
          "Research metrics",
          "Resource lists",
          "Resource sharing",
          "RFID",
          "RDM",
          "RIMS",
          "Software",
          "Special collections",
          "Technology market",
          "VLE",
          "Virtual Learning Environment",
          "Who uses what",
        ],
    }

collections:
  - label: "Title pages"
    name: "pages"
    files:
      - name: analytics_and_user_engagement_index
        label: Analytics and user engagement
        file: analytics-and-user-engagement/index.md
        create: false
        fields:
          - *TITLE
          - *BODY
          - *META_TAGS
          - *DEFAULT_LAYOUT
          - {
              label: "Navigation order",
              name: "nav_order",
              widget: "hidden",
              default: 10,
            }
          - {
              label: "Has children",
              name: "has_children",
              widget: "hidden",
              default: true,
            }

      - name: archives_and_special_collections_index
        label: Archives and special collections
        file: archives-and-special-collections/index.md
        create: false
        fields:
          - *TITLE
          - *BODY
          - *META_TAGS
          - {
              label: "Navigation order",
              name: "nav_order",
              widget: "hidden",
              default: 11,
            }
          - {
              label: "Has children",
              name: "has_children",
              widget: "hidden",
              default: true,
            }

      - name: core_library_systems_index
        label: Core library systems
        file: core-library-systems/index.md
        create: false
        fields:
          - *TITLE
          - *BODY
          - *META_TAGS
          - {
              label: "Navigation order",
              name: "nav_order",
              widget: "hidden",
              default: 6,
            }
          - {
              label: "Has children",
              name: "has_children",
              widget: "hidden",
              default: true,
            }

      - name: discovery_and_content_index
        label: Discovery and content
        file: discovery-and-content/index.md
        create: false
        fields:
          - *TITLE
          - *BODY
          - *META_TAGS
          - {
              label: "Navigation order",
              name: "nav_order",
              widget: "hidden",
              default: 7,
            }
          - {
              label: "Has children",
              name: "has_children",
              widget: "hidden",
              default: true,
            }

      - name: events_index
        label: Events
        file: events/index.md
        create: false
        fields:
          - *TITLE
          - *BODY
          - *META_TAGS
          - *DEFAULT_LAYOUT
          - {
              label: "Navigation order",
              name: "nav_order",
              widget: "hidden",
              default: 3,
            }
          - {
              label: "Has children",
              name: "has_children",
              widget: "hidden",
              default: true,
            }

      - name: past_events_index
        label: Past events
        file: events/past-events/index.md
        create: false
        fields:
          - *TITLE
          - *BODY
          - *META_TAGS
          - *DEFAULT_LAYOUT
          - {
              label: "Navigation order",
              name: "nav_order",
              widget: "hidden",
              default: 1,
            }
          - {
              label: "Has children",
              name: "has_children",
              widget: "hidden",
              default: true,
            }

      - name: learning_and_teaching_tech_index
        label: Learning and teaching tech
        file: learning-and-teaching-tech/index.md
        create: false
        fields:
          - *TITLE
          - *BODY
          - *META_TAGS
          - *DEFAULT_LAYOUT
          - {
              label: "Navigation order",
              name: "nav_order",
              widget: "hidden",
              default: 8,
            }
          - {
              label: "Has children",
              name: "has_children",
              widget: "hidden",
              default: true,
            }

      - name: news_index
        label: News
        file: news/index.md
        create: false
        fields:
          - *TITLE
          - *BODY
          - *META_TAGS
          - *DEFAULT_LAYOUT
          - {
              label: "Navigation order",
              name: "nav_order",
              widget: "hidden",
              default: 2,
            }
          - {
              label: "Has children",
              name: "has_children",
              widget: "hidden",
              default: true,
            }

      - name: news_archive_index
        label: News archive
        file: news/archive/index.md
        create: false
        fields:
          - *TITLE
          - *BODY
          - *META_TAGS
          - *DEFAULT_LAYOUT
          - {
              label: "Navigation order",
              name: "nav_order",
              widget: "hidden",
              default: 1,
            }
          - {
              label: "Has children",
              name: "has_children",
              widget: "hidden",
              default: true,
            }

      - name: product_directory
        label: Product directory
        file: product-directory/index.md
        create: false
        fields:
          - *TITLE
          - *BODY
          - *META_TAGS
          - *DEFAULT_LAYOUT
          - {
              label: "Navigation order",
              name: "nav_order",
              widget: "hidden",
              default: 5,
            }
          - {
              label: "Has children",
              name: "has_children",
              widget: "hidden",
              default: false,
            }

      - name: research_management_index
        label: Research management
        file: research-management/index.md
        create: false
        fields:
          - *TITLE
          - *BODY
          - *META_TAGS
          - *DEFAULT_LAYOUT
          - {
              label: "Navigation order",
              name: "nav_order",
              widget: "hidden",
              default: 9,
            }
          - {
              label: "Has children",
              name: "has_children",
              widget: "hidden",
              default: true,
            }

      - name: who_uses_what_index
        label: Who uses what
        file: who-uses-what/index.md
        create: false
        fields:
          - *TITLE
          - *BODY
          - *META_TAGS
          - *DEFAULT_LAYOUT
          - {
              label: "Navigation order",
              name: "nav_order",
              widget: "hidden",
              default: 4,
            }
          - {
              label: "Has children",
              name: "has_children",
              widget: "hidden",
              default: true,
            }

  - name: "news_posts"
    label: "News posts"
    folder: "News"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    filter:
      field: parent
      value: News
    fields:
      - *TITLE
      - *DATE_ADDED
      - *SYNOPSIS
      - *META_TAGS
      - *BODY
      - *DEFAULT_LAYOUT
      - { label: "Parent", name: "parent", widget: "hidden", default: "News" }

  - name: "news_archive"
    label: "News archive"
    folder: "news/archive"
    create: false
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    filter:
      field: parent
      value: News archive
    fields:
      - *TITLE
      - *DATE_ADDED
      - *SYNOPSIS
      - *META_TAGS
      - *BODY
      - *DEFAULT_LAYOUT
      - {
          label: "Parent",
          name: "parent",
          widget: "hidden",
          default: "News archive",
        }

  - name: "events"
    label: "Events"
    folder: "events"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    filter:
      field: parent
      value: Events
    fields:
      - *TITLE
      - *DATE
      - *ABSTRACT
      - *META_TAGS
      - *BODY
      - *DEFAULT_LAYOUT
      - { label: "Parent", name: "parent", widget: "hidden", default: "Events" }

  - name: "past_events"
    label: "Past events"
    folder: "events/past-events"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    filter:
      field: parent
      value: Past events
    fields:
      - *TITLE
      - *DATE
      - *ABSTRACT
      - *META_TAGS
      - *BODY
      - *DEFAULT_LAYOUT
      - {
          label: "Parent",
          name: "parent",
          widget: "hidden",
          default: "Past events",
        }

  - name: "analytics_and_user_engagement"
    label: "Analytics and user engagement"
    folder: "analytics-and-user-engagement"
    create: true
    filter:
      field: parent
      value: Analytics and user engagement
    fields:
      - *TITLE
      - *META_TAGS
      - *BODY
      - *DEFAULT_LAYOUT
      - {
          label: "Parent",
          name: "parent",
          widget: "hidden",
          default: "Analytics and user engagement",
        }

  - name: "archives_and_special_collections"
    label: "Archives and special collections"
    folder: "archives-and-special-collections"
    create: true
    filter:
      field: parent
      value: Archives and special collections
    fields:
      - *TITLE
      - *META_TAGS
      - *BODY
      - *DEFAULT_LAYOUT
      - {
          label: "Parent",
          name: "parent",
          widget: "hidden",
          default: "Archives and special collections",
        }

  - name: "core_library_systems"
    label: "Core library systems"
    folder: "core-library-systems"
    create: true
    filter:
      field: parent
      value: Core library systems
    fields:
      - *TITLE
      - *META_TAGS
      - *BODY
      - *DEFAULT_LAYOUT
      - {
          label: "Parent",
          name: "parent",
          widget: "hidden",
          default: "Core library systems",
        }

  - name: "discovery_and_content"
    label: "Discovery and content"
    folder: "discovery-and-content"
    create: true
    filter:
      field: parent
      value: Discovery and content
    fields:
      - *TITLE
      - *META_TAGS
      - *BODY
      - *DEFAULT_LAYOUT
      - {
          label: "Parent",
          name: "parent",
          widget: "hidden",
          default: "Discovery and content",
        }

  - name: "learning_and_teaching_tech"
    label: "Learning and teaching tech"
    folder: "learning-and-teaching-tech"
    create: true
    filter:
      field: parent
      value: Learning and teaching tech
    fields:
      - *TITLE
      - *META_TAGS
      - *BODY
      - *DEFAULT_LAYOUT
      - {
          label: "Parent",
          name: "parent",
          widget: "hidden",
          default: "Learning and teaching tech",
        }

  - name: "research_management"
    label: "Research management"
    folder: "research-management"
    create: true
    filter:
      field: parent
      value: Research management
    fields:
      - *TITLE
      - *META_TAGS
      - *BODY
      - *DEFAULT_LAYOUT
      - {
          label: "Parent",
          name: "parent",
          widget: "hidden",
          default: "Research management",
        }

  - name: "who_uses_what"
    label: "Who uses what"
    folder: "who-uses-what"
    create: true
    filter:
      field: parent
      value: Who uses what
    fields:
      - *TITLE
      - *META_TAGS
      - *BODY
      - *DEFAULT_LAYOUT
      - {
          label: "Parent",
          name: "parent",
          widget: "hidden",
          default: "Who uses what",
        }
